# Railway service definition.
# Docs: https://docs.railway.app/guides/config-as-code

[build]
# Use custom Nixpacks configuration for system dependencies.
nixpacksConfigPath = "nixpacks.toml"

[deploy]
# Set the start command for the application.
startCommand = "python run.py"

# Restart the service on failure.
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 